name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Custom SSH Deploy
        env:
          DEPLOY_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USERNAME }}
        run: |
          # Setup SSH Key
          SSH_DIR="$HOME/.ssh"
          mkdir -p "$SSH_DIR"
          echo "$DEPLOY_SSH_KEY" > "$SSH_DIR/deploy_key"
          chmod 600 "$SSH_DIR/deploy_key"

          # Disable Host Key Checking
          echo -e "Host *\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null\n" > "$SSH_DIR/config"

          # Rsync Over SSH
          rsync -avz -e "ssh -i $SSH_DIR/deploy_key" \
            --exclude='.git/*' \
            --exclude='node_modules/*' \
            ./ $SERVER_USER@$SERVER_IP:/var/www/worldofunreal.com

          # Post-Deployment Commands (e.g., restart Apache)
          ssh -i $SSH_DIR/deploy_key $SERVER_USER@$SERVER_IP "sudo systemctl restart apache2"
